name: CI - Pull Request Open

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: ["!master"]
  pull_request:
    branches: [master]
    types:
      - synchronize
      - opened
      - edited
      - reopened
      - unlocked

jobs:
  test:
    uses: notarise-gov-sg/workflows/.github/workflows/deploy-ci-open.yml@feat/cypress-api-test
    with:
      deploy: false
